---
title: "Bolletin Tema1"
subtitle: Tratamiento de Datos. Grado en Ciencia de Datos- UV
author: "Sofia MABROUK"
#Pone la fecha de generación del documento
date:  "`r Sys.Date()`"  #Pondría la fecha del día actual
# Para que en lugar de "Contents" ponga "Indice" al incluir la tabla de contenido

params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"

# Por defecto se generará un salida html
# Si si quieres otras salidas o varias de ellas descomenta lo que proceda
output:
# Salida pdf. Si se incluye código en LaTex necesitarás tener instalado un compilador de Latex
  pdf_document:
    toc: yes      # Tabla de contenido (índice)
    toc_depth: 3  # Número de niveles de la tabla de contenido (índice) # 1, ##2,###3
#    number_sections: yes # Numeración de las secciones
# Salida html, 
  html_document:
    echo: yes
    number_sections: yes
    theme: lumen    # Aspecto y estilo,otras opciones: cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti 
    toc: yes
# Salida html_notebook, como html, pero con algunas opciones de visualización
  html_notebook:
    echo: yes
    number_sections: yes
    toc: yes
# Esto nos permite traducir estas etiquetas para que aparezcan en otro idioma en caso de que se usen en el documento para referenciar a figuras, tablas, etc
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---

# Introducción
This is a solution for the exercice in Bolletin Tema1

#Exercice 1

```{r }
#load the robustbase package
library(robustbase)
library(MASS)
?Animals2
?mammals

#data inspection
dim(mammals)
dim(mammals)
tail(mammals)
str(mammals)

dim(Animals2)
dim(Animals2)
tail(Animals2)
str(Animals2)

# Display the row names of the mammals dataset
rownames(mammals)
# Display the column names of the mammals dataset
colnames(mammals)
# Display the row names of the Animals2 dataset
rownames(Animals2)
# Display the column names of the Animals2 dataset
colnames(Animals2)

# Get the animal names from the "mammals" dataset
animals_mammals <- rownames(mammals)
# Get the animal names from the "Animals2" dataset
animals_Animals2 <- rownames(Animals2)


# Find the common animals using the intersect() function
commonAnimals <- intersect(animals_mammals, animals_Animals2)
# Print the common animals
commonAnimals


# Find the animals that are not in both datasets using the setdiff() function
notCommonAnimals <- setdiff(union(animals_mammals, animals_Animals2), intersect(animals_mammals, animals_Animals2))

# Count the number of animals that are not in both datasets
numNotCommonAnimals <- length(notCommonAnimals)

# Print the number of animals and their types
cat("Number of animals not in both datasets:", numNotCommonAnimals, "\n")
cat("Types of animals not in both datasets:", notCommonAnimals, "\n")


# Find the animals that are not in both datasets using the setdiff() function
animals_diff  <- setdiff(animals_mammals, animals_Animals2)
# Print the animals that do not appear in both datasets
cat("Animals that do not appear in both datasets:", animals_diff, "\n")


```

#Exercice 2
```{r}
library(car)

# Get the log of brain weights from the "mammals" dataset
brain_weights_mammals <- log(mammals$brain)

# Get the log of brain weights from the "Animals2" dataset
brain_weights_Animals2 <- log(Animals2$brain)

# Create a QQ plot for the log brain weights of "mammals"
qqPlot(brain_weights_mammals, main = "QQ Plot - Mammals")

# Create a QQ plot for the log brain weights of "Animals2"
qqPlot(brain_weights_Animals2, main = "QQ Plot - Animals2")
```
--------> As we can see in the graphic, the samples are within the dashed lines, so
we can indicate that they follow a Gaussian distribution with 95 % confidence.

#Exercice 4
The first three stages for the "cabbages" dataset in the MASS package would be:
Data Exploration:
    .Use functions like head() and summary() to get an initial overview of the dataset.
    .Examine the structure and dimensions of the dataset using str().
    .Identify the variables and their types (numeric, categorical, etc.).
    .Check for missing.
    
Data Visualization:
     .Create graphs, such as histograms, box plots, scatter plots... to explore the distribution and relationships of variables.
     .Look for patterns or outliers.
     
Data Preprocessing:
      .Handle missing data by imputation or deletion.
      .Deal with outliers
      .Perform any necessary data transformations, such as scaling or creating new variables based on existing ones.
```{r}
library(carData)
data(cabbages)
data(Chile)

# Count the number of missing values for each variable
missing_values_cab <- sapply(cabbages, function(x) sum(is.na(x)))
# Print the number of missing values for each variable
print(missing_values_cab)

# Data Exploration for "Chile"
#head(Chile)
#summary(Chile)
#str(Chile)
missing_values_chile <- sapply(Chile, function(x) sum(is.na(x)))
print(missing_values_chile)

# Use the summary() function on the "cabbages" dataset
summary(cabbages)
# Use the summary() function on the "Chile" dataset
summary(Chile)

```
-----> As we can see, the summary function gives also the number of NA values (NA's) when they exist

